# SETTINGS
[note]

language = "en"
default-title = "Untitled"
extension = "md"
template = "default.md"

# Neuron compatibility
filename = "{{id}}"
id-charset = "hex"
id-length = 8
id-case = "lower"


[extra]

author = "jaimecgomezz"


[group.daily]

paths = ["journal"]

[group.daily.note]

filename = "{{format-date now '%Y%m%d'}}"
extension = "md"
template = "daily.md"


[format.markdown]

link-format = "wiki"
hashtags = true
colon-tags = true


[tool]

editor = "nvim"
pager = "nvim"
fzf-preview = "bat -p --color always {-1}"


[lsp]

[lsp.diagnostics]

wiki-title = "hint"
dead-link = "error"

[lsp.completion]
# Show the note title in the completion pop-up, or fallback on its path if empty.
note-label = "{{title-or-path}}"
# Filter out the completion pop-up using the note title or its path.
note-filter-text = "{{title}} {{path}}"
# Show the note filename without extension as detail.
note-detail = "{{filename-stem}}"


[alias]

# Edit the last modified note.
last = 'zk edit --limit 1 --sort modified- "$@"'

# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# Show a random note.
lucky = "zk list --quiet --format full --sort random --limit 1"

# list notes for editing
ls = "zk edit --interactive"

# sear notes by tags
tag = "zk edit --interactive --tag \"$@\""

config = 'nvim "$HOME/.config/zk/config.toml"'

# new journal entry
daily = 'zk --no-input new $ZK_NOTEBOOK_DIR/journal'

# new note
new = "zk new  $ZK_NOTEBOOK_DIR/ideas --title \"$@\""

journal = "zk edit --sort created- $ZK_NOTEBOOK_DIR/journal --interactive"

ideas = "zk edit --sort created- $ZK_NOTEBOOK_DIR/ideas --interactive"

# update zk notes
update = "cd $ZK_NOTEBOOK_DIR; git add -A; git commit -am 'updating'; git push; cd -"

# remove a files
rm = "zk list --interactive --quiet --format path --delimiter0 \"$@\" | xargs -0 rm -vf --"

# open last zk in slides
slides = "zk list --interactive --quiet --format path --delimiter0 \"$@\" | xargs -0 slides"
